services:
  php71:
    build:
      context: docker/php71
      target: base
    volumes:
      - ./:/app
      - ./docker/php71:/usr/local/etc/php

  php71debug:
    build:
      context: docker/php71
      target: debug
    volumes:
      - ./:/app
      - ./docker/php71:/usr/local/etc/php

  php71composer:
    build:
      context: docker/php71
      target: composer
    volumes:
      - ./:/app